### ISSUE TITLE
how to exclude page numbers in camera-ready paper?

### ISSUE THREAD

**Issue by yuliangguo** [wacv-pcs/WACV-2022-Author-Kit#3]
The camera-ready instruction requests "Do not include page numbers in your camera-ready paper."  However, I found the latex use "\setcounter{page}{\assignedStartPage}", which requires a assigned assigned start page. If I force to use "\pagestyle{empty}", there is still a number on page 1.

Does anyone know what is the right way to handle such issue?

**Comment by thiagoluange** [comment]
Based on older wacv templates, I forced to use "\pagestyle{empty}" and I forced  on page one again.
...
\begin{document}
%%%%%%%%% TITLE
\title{\LaTeX\ Author Guidelines for WACV Proceedings}

\author{First Author\\
Institution1\\
Institution1 address\\
{\tt\small firstauthor@i1.org}
% For a paper whose authors are all at the same institution,
% omit the following lines up until the closing ``}''.
% Additional authors and addresses can be added with ``\and'',
% just like the second author.
% To save space, use either the email address or home page, not both
\and
Second Author\\
Institution2\\
First line of institution2 address\\
{\tt\small secondauthor@i2.org}
}
\maketitle
\ifwacvfinal\thispagestyle{empty}\fi  %put this commond here

**Comment by yuliangguo** [comment]
> Based on older wacv templates, I forced to use "\pagestyle{empty}" and I forced on page one again. ... \begin{document} %%%%%%%%% TITLE \title{\LaTeX\ Author Guidelines for WACV Proceedings}
> 
> \author{First Author\ Institution1\ Institution1 address\ {\tt\small [firstauthor@i1.org](mailto:firstauthor@i1.org)} % For a paper whose authors are all at the same institution, % omit the following lines up until the closing `}''. % Additional authors and addresses can be added with `\and'', % just like the second author. % To save space, use either the email address or home page, not both \and Second Author\ Institution2\ First line of institution2 address\ {\tt\small [secondauthor@i2.org](mailto:secondauthor@i2.org)} } \maketitle \ifwacvfinal\thispagestyle{empty}\fi %put this commond here

Thank you so much for the reply. Problem solved.
